export type PixelGrid = readonly string[];
export type PixelAnimation = readonly [PixelGrid, ...PixelGrid[]];

export const CLASSIC_SPRITES = {
  player: {
    center: [
      [
        '.....C.....',
        '....CCC....',
        '...CCCCC...',
        'C....C....C',
        'C.CCCCCCC.C',
        'CCCCCCCCCCC',
        'CC.......CC',
      ],
      [
        '.....C.....',
        '....CCC....',
        '...CCCCC...',
        'C....C....C',
        'C.CCCCCCC.C',
        'CCCCCCCCCCC',
        '.C.......C.',
      ],
    ],
    left: [
      [
        '....C......',
        '...CCC.....',
        '..CCCCC....',
        'C...C.....C',
        'CCCCCCCC..C',
        'CCCCCCCCCCC',
        'CC.......CC',
      ],
      [
        '....C......',
        '...CCC.....',
        '..CCCCC....',
        'C...C.....C',
        'CCCCCCCC..C',
        'CCCCCCCCCCC',
        '.C.......C.',
      ],
    ],
    right: [
      [
        '......C....',
        '.....CCC...',
        '....CCCCC..',
        'C.....C...C',
        'C..CCCCCCCC',
        'CCCCCCCCCCC',
        'CC.......CC',
      ],
      [
        '......C....',
        '.....CCC...',
        '....CCCCC..',
        'C.....C...C',
        'C..CCCCCCCC',
        'CCCCCCCCCCC',
        '.C.......C.',
      ],
    ],
  } satisfies Record<string, PixelAnimation>,
  life: [
    '.....G.....',
    '....GGG....',
    '...GGGGG...',
    'G....G....G',
    'G.GGGGGGG.G',
    'GGGGGGGGGGG',
    'GG.......GG',
  ] satisfies PixelGrid,
  flagship: [
    [
      'P.....P.....P',
      'PP...PPP...PP',
      '.PP.P.P.P.PP.',
      '..PPPPPPPPP..',
      '...PP.P.PP...',
      '....PPPPP....',
      '.....PPP.....',
      '......P......',
      '.............',
    ],
    [
      '.P....P....P.',
      '.PP..PPP..PP.',
      '..PPP.P.PPP..',
      '...PPPPPPP...',
      '..PPP.P.PPP..',
      '...PPPPPPP...',
      '.....PPP.....',
      '......P......',
      '.............',
    ],
  ] satisfies PixelAnimation,
  scout: [
    [
      '..P.......P..',
      '...P.....P...',
      '.PPPPPPPPPPP.',
      'PPP..PPP..PPP',
      '.PP..PPP..PP.',
      '..PPPPPPPPP..',
      '...PPPPPPP...',
      '....P...P....',
      '.............',
    ],
    [
      '...P.....P...',
      '..P.......P..',
      '.PPPPPPPPPPP.',
      'PPP..PPP..PPP',
      '.PP..PPP..PP.',
      '..PPPPPPPPP..',
      '...PPPPPPP...',
      '...P.....P...',
      '.............',
    ],
  ] satisfies PixelAnimation,
  striker: [
    [
      '.P.........P.',
      '.PP..P.P..PP.',
      '..PPPPPPPPP..',
      'PPP..PPP..PPP',
      '..P..PPP..P..',
      '...PPPPPPP...',
      '..PP..P..PP..',
      '.P....P....P.',
      '.............',
    ],
    [
      '..P.......P..',
      '..PP.P.P.PP..',
      '...PPPPPPP...',
      'PPP..PPP..PPP',
      '..P..PPP..P..',
      '...PPPPPPP...',
      '.PPP..P..PPP.',
      '.P....P....P.',
      '.............',
    ],
  ] satisfies PixelAnimation,
  drone: [
    [
      '....PPPPP....',
      '..PPPPPPPPP..',
      '.PP..PPP..PP.',
      'PPP..PPP..PPP',
      '.PPPPPPPPPPP.',
      '..PPPPPPPPP..',
      '...PP...PP...',
      '..P.......P..',
      '.............',
    ],
    [
      '....PPPPP....',
      '..PPPPPPPPP..',
      '.PP..PPP..PP.',
      'PPP..PPP..PPP',
      '.PPPPPPPPPPP.',
      '..PPPPPPPPP..',
      '...PP...PP...',
      '....P...P....',
      '.............',
    ],
  ] satisfies PixelAnimation,
  manta: [
    [
      '.P.........P.',
      '..P.......P..',
      '...PPPPPPP...',
      '.PPP.PPP.PPP.',
      'PPP..PPP..PPP',
      '.PPPPPPPPPPP.',
      '...PPPPPPP...',
      '..PP.....PP..',
      '.............',
    ],
    [
      '..P.......P..',
      '.P.........P.',
      '...PPPPPPP...',
      '.PPP.PPP.PPP.',
      'PPP..PPP..PPP',
      '.PPPPPPPPPPP.',
      '...PPPPPPP...',
      '....P...P....',
      '.............',
    ],
  ] satisfies PixelAnimation,
  raider: [
    [
      '...P.....P...',
      '..PPPPPPPPP..',
      '.PPP.PPP.PPP.',
      'PPP..PPP..PPP',
      '..PPPPPPPPP..',
      '...PPPPPPP...',
      '..PP.....PP..',
      '.P.........P.',
      '.............',
    ],
    [
      '..P.......P..',
      '..PPPPPPPPP..',
      '.PPP.PPP.PPP.',
      'PPP..PPP..PPP',
      '..PPPPPPPPP..',
      '...PPPPPPP...',
      '..PP.....PP..',
      '...P.....P...',
      '.............',
    ],
  ] satisfies PixelAnimation,
  playerBullet: ['W', 'W', 'W', 'W', 'W'] satisfies PixelGrid,
  enemyBullet: ['W', 'W', 'W', 'W'] satisfies PixelGrid,
  explosion: [
    [
      '.........',
      '....Y....',
      '..Y.Y.Y..',
      '...YYY...',
      '.YYYYYYY.',
      '...YYY...',
      '..Y.Y.Y..',
      '....Y....',
      '.........',
    ],
    [
      '....Y....',
      '.Y.....Y.',
      '..Y...Y..',
      '...Y.Y...',
      'YY.....YY',
      '...Y.Y...',
      '..Y...Y..',
      '.Y.....Y.',
      '....Y....',
    ],
    [
      'Y.......Y',
      '....R....',
      '.........',
      '.........',
      '.R.....R.',
      '.........',
      '.........',
      '....R....',
      'Y.......Y',
    ],
    [
      'R.......R',
      '.........',
      '.........',
      '.........',
      '.........',
      '.........',
      '.........',
      '.........',
      'R.......R',
    ],
  ] satisfies PixelAnimation,
};
